### ISSUE TITLE
Custom Fields aren't picked up if created via our public example

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-CSV-Toolbox#2]
We have detailed docs and a live plugin example of how to create custom fields:

1. [Live example plugin](https://github.com/WordImpress/Give-Snippet-Library/blob/master/form-customizations/custom-fields-plugin.php)

2.  [Documentation](https://givewp.com/documentation/developers/how-to-create-custom-form-fields/)

Using either of those as a basis for creating custom fields doesn't allow the CSV Toolbox to recognize those fields as available for populating. 

## STEPS TO REPRODUCE
1. Use the example plugin to add fields to a form (change the form ID accordinginly in the code)
2. Make a donation
3. Confirm the data appears correctly in the Donation Details screen
4. Try to use CSV Toolbox to export that data from that form and the "Custom Fields Columns" section will say "No fields".

**Comment by mathetos** [comment]
Just an update, Devin updated the public documentation to store the data in a more future-proof way. So we'll have less and less users using the old method that doesn't work, but we still have several folks in need of this functionality.

**Comment by Benunc** [comment]
I used the new method for saving the data, and I'm still not able to access the new custom form fields added. A user needed a custom hidden field that populates with the page the form is embedded in, so I made this snippet:

```
<?php

function my_give_add_hidden_field_with_slug() {
	?>

	<div id="my-give-slug-wrap" class="form-row  give-hidden"><label class="give-label" for="my-give-slug">
			Page donated from </label>
		<input class="textfield"
		       id="my-give-slug"
		       type="text"
		       data-required="no"
		       data-type="text"
		       name="give_slug"
		       placeholder=""
		       value="<?php
		       global $post;
		       $post_slug = $post->post_name;
		       echo $post_slug; ?>"
		       size="40"/>

	</div>

	<?php
}

add_action( 'give_after_donation_levels', 'my_give_add_hidden_field_with_slug' );

function my_give_donations_save_slug( $payment_id, $payment_data ) {
	if ( isset( $_POST['give_slug'] ) ) {
		$message = implode( "\n", array_map( 'sanitize_text_field', explode( "\n", $_POST['give_slug'] ) ) );
		add_post_meta( $payment_id, '_give_slug', $message );
	}
}

add_action( 'give_insert_payment', 'my_give_donations_save_slug', 10, 2 );

function my_give_display_slug( $payment_meta, $user_info ) {
	// Bounce out if no data for this transaction
	$give_slug = get_post_meta( $payment_meta, '_give_slug', true );
	if ( $give_slug ) : ?>
		<div class="slug-data give-admin-box-inside">
			<p><strong><?php _e( 'Page donated from:', 'give' ); ?></strong><br/>
				<?php echo $give_slug; ?></p>
		</div>
	<?php endif;
}

add_action( 'give_view_order_details_payment_meta_before', 'my_give_display_slug', 10, 2 );
```
Which correctly adds the field to the back end of the site:

<img width="290" alt="screen shot 2017-06-05 at 11 53 06 am" src="https://cloud.githubusercontent.com/assets/9629102/26791898/97d73e20-49e6-11e7-9047-10e8ff9362fc.png">

But it is still not picked up by the CSV toolbox.
